sonar.projectKey=hackathom-fiap_fiapx-app-api
sonar.organization=hackathom-fiap
sonar.host.url=https://sonarcloud.io

# Onde está o código e os binários
sonar.sources=src/main/java
sonar.java.binaries=target/classes

# Configurações de encoding e linguagem
sonar.sourceEncoding=UTF-8
sonar.language=java

# Relatório de cobertura do JaCoCo (gerado pelo Maven)
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Exclusões para aumentar a porcentagem de cobertura (focar em lógica de negócio)
sonar.exclusions=src/main/java/com/fiapx/video/infrastructure/config/**,src/main/java/com/fiapx/video/application/dto/**,src/main/java/com/fiapx/video/infrastructure/adapter/persistence/entity/**,src/main/java/com/fiapx/video/infrastructure/adapter/web/dto/**,src/main/java/com/fiapx/video/VideoApiApplication.java


# Define a branch principal
sonar.branch.name=main
