apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-api
  namespace: hackathon-video-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-api
  template:
    metadata:
      labels:
        app: video-api
    spec:
      containers:
      - name: video-api
        image: fiap-x-video-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082
        envFrom:
        - configMapRef:
            name: video-api-config
        - secretRef:
            name: video-api-secret
        volumeMounts:
        - name: video-storage
          mountPath: /tmp/videos
      volumes:
      - name: video-storage
        persistentVolumeClaim:
          claimName: video-shared-pvc
