apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-api
  namespace: hackathon-video-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-api
  template:
    metadata:
      labels:
        app: video-api
    spec:
      serviceAccountName: api-service-account # Para o pod usar a Role do S3
      containers:
      - name: video-api
        image: 239409137076.dkr.ecr.us-east-1.amazonaws.com/api:TAG
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082
        envFrom:
        - configMapRef:
            name: video-api-config
        - secretRef:
            name: video-api-secret
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
